- build-aux/vs2019/libbitcoin_common/libbitcoin_common.props
- build-aux/vs2019/libbitcoin_server/libbitcoin_server.props
- build-aux/vs2019/libbitcoin_util/libbitcoin_util.props
- build-aux/vs2019/libbitcoin_wallet/libbitcoin_wallet.props
- build-aux/vs2019/pastel-cli/pastel-cli.props
- build-aux/vs2019/pasteld/pasteld.props
- build-aux/vs2019/settings/common.props
- build-aux/vs2019/settings/pastel_common.props
- src/coins.cpp
- src/coins.h
- src/init.cpp
- src/main.cpp
- src/main.h
- src/memusage.h
- src/metrics.cpp
- src/rpc/client.cpp
- src/script/sigcache.cpp
- src/serialize.h
- src/streams.h
- src/support/allocators/secure.h
- src/support/allocators/zeroafterfree.h
- src/txmempool.cpp
- src/wallet/asyncrpcoperation_mergetoaddress.cpp
- src/wallet/asyncrpcoperation_sendmany.cpp
- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
- src/wallet/wallet.h
- src/wallet/wallet_ismine.cpp
- src/wallet/wallet_ismine.h
- implemented new parameter for "listaddressamounts" rpc command:
ismineFilter (string, optional, default=all) Whether to include "all", "watchOnly" or "spendableOnly" addresses
- fixed "listaddressamounts" includeEmpty boolean parameter conversion to json in pastel-cli
- fixed VT console sequences for win32 - showmetrics correctly on win32
Visual Studio 2019 support:
-changed cpp standard in common.props to stdcpp17
-fixed c++17 compilation issues
-replaced boost::unordered_map|unordered_set with std::unordered_map|unordered_set,
these boost containers merged into c++17 standard
-added pastel_common.props property sheet
> 38417834: add new parameter "mine" to "listaddressamounts", to return only spendable addresses

- depends/packages/libsodium.mk
Libsodium changed download path for 1.0.15. Moved to unsupported.
New download path for libsodium: https://download.libsodium.org/libsodium/releases/old/unsupported/
> libsodium 1.0.15 moved to unsupported

- src/Makefile.am
- src/clientversion.h
- src/dbwrapper.h
- src/ed448/pastel_key.h
- src/mnode-pastel.cpp
- src/mnode-pastel.h
- src/mnode-rpc.cpp
- src/prevector.h
- src/rpc/rpc_parser.h
- src/script/script.h
38417841: add new parameter "mine" to "tickets list id", to return registered PastelIDs that are available on the local cNode
-implemented new filter parameter "mine" for "tickets list id" rpc command:
id     - List PastelID registration tickets. Without filter parameter lists ALL (both masternode and personal) PastelIDs.
Filter:
all      - lists all masternode PastelIDs. Default.
mn       - lists only masternode PastelIDs.
personal - lists only personal PastelIDs.
mine     - lists only registered PastelIDs available on the local node.
-improved rpc commands parsing, new class RPCCommandParser
-corrected help info for some rpc commands (changed to R-strings to simplify syntax)
> 38417841: add new parameter "mine" to "tickets list id", to return registered PastelIDs that are available on the local cNode

- qa/rpc-tests/mn_governance__custom_test.py
- src/gtest/test_mnode_governance.cpp
- src/mnode/mnode-governance.cpp
- src/mnode/mnode-governance.h
- src/mnode/mnode-rpc.cpp
- src/mnode/mnode-validation.cpp
- src/secp256k1/src/field_10x26_impl.h
To fix all V1028 PVS warnings in src/secp256k1/src/field_10x26_impl.h
Result:
- Built successfully
- PVS report show no warnings for all the issues on column (Pastel (Fixed by this commit))
- Passed all circleci test cases
- Passed all below test suite on local machine:
cd qa/test-suite
./full_test_suite.py btest
./full_test_suite.py gtest
./full_test_suite.py sec-hard
./full_test_suite.py no-dot-so
./full_test_suite.py util-test
./full_test_suite.py secp256k1
./full_test_suite.py libsnark
./full_test_suite.py univalue
./full_test_suite.py rpc-common
./full_test_suite.py rpc-ext
Test case that took too long to complete, and failed some test cases while running:
./full_test_suite.py rpc-mn
> Fix HIGH PVS warnings for secp256 arithmetic

- qa/rpc-tests/mn_tickets.py
- src/mnode/mnode-pastel.cpp
- src/mnode/mnode-pastel.h
- src/mnode/mnode-rpc.cpp
- src/mnode/ticket-processor.cpp
- src/mnode/ticket-processor.h
- src/mnode/ticket.h
1) Add additional fields to tickets (freedcamp - 39157067)
a) ID ticket: legroast public key
b) Art Registration ticket: royalty and Green NFT address
2) Removed "silent upgrade" of ticket versions
3) Added methods to "walk back to art registration ticket" from future trade tickets
4) mn_tickets test:
a) "high heights" tests disabled by default and fixed counters;
b) ticket prices changed
5) Draft of logic to support royalty and Green NFT payments
Tests:
<<< TEST SUCCEDED >>>
--- Success: mn_tickets --- | exectime: 01:09:47.762
> tickets updates; royalty and Green NFT; ticket prices back to 10

- qa/rpc-tests/mn_tickets.py
- src/mnode/mnode-controller.cpp
- src/mnode/mnode-controller.h
- src/mnode/mnode-masternode.cpp
- src/mnode/mnode-masternode.h
- src/mnode/mnode-rpc.cpp
This commit is to implement: 
+ https://freedcamp.com/view/2956206/tasks/40506963
+ https://freedcamp.com/view/2956206/tasks/40507034
Follow the code of `storagefee getnetworkfee` and add similar logic for `storagefee getartticketfee`
- Create method CAmount CMasterNodeController::GetArtTicketFeePerKB()
- Use `ArtTicketFeePerKBDefault` for default value and set it to 3
Change MasternodeFeePerMBDefault to 50
> Add APIs: storagefee getnetworkfee, tickets tools gettotalstoragefee

- .circleci/config.yml
Change circle-ci config:
+ `xlarge `-->` medium+`
+ -j16 to -j2
Open all 3 build systems: MacOS, Windows, Linux and check if
+ The Executor changed to `Docker Medium+`:
+ At the start of "Building Pastel Core" log, check if `-j2` is used.
This change does not effect source code so no need to run test cases to validate.
> Update circle-ci configurations

- qa/rpc-tests/mn_governance.py
Fix issue that cause mn_governance.py failed randomly.
Root cause: The current test didn't wait long enough for nodes to sync, so sometimes the test cases failed, sometimes the test cases passed.
Solution: Increase waiting time to make sure all nodes synced.
##What is the test result?
- Built successfully
- Passed all below test suite on local machine:
cd qa/test-suite
./mn_governance.py
./mn_main.py
./mn_payment.py
./mn_tickets.py
./mn_tickets_validation.py
./mn_messaging.py
./full_test_suite.py btest
./full_test_suite.py gtest
./full_test_suite.py sec-hard
./full_test_suite.py no-dot-so
./full_test_suite.py util-test
./full_test_suite.py secp256k1
./full_test_suite.py libsnark
./full_test_suite.py univalue
./full_test_suite.py rpc-common
./full_test_suite.py rpc-ext
Test case that took …
> Fix issue that cause mn_governance.py failed randomly

- qa/rpc-tests/wallet_sapling.py
- src/wallet/asyncrpcoperation_sendmany.cpp
- src/wallet/asyncrpcoperation_sendmany.h
- src/wallet/rpcwallet.cpp
Add implementation for z_sendmanywithchangetosender, which will send PSL to an address and return any change to the sending address
Built successfully
Passed all below test suite on local machine:
cd qa/test-suite
./mn_main.py
./mn_payment.py
./mn_tickets.py
./mn_tickets_validation.py
./mn_messaging.py
./full_test_suite.py btest
./full_test_suite.py gtest
./full_test_suite.py sec-hard
./full_test_suite.py no-dot-so
./full_test_suite.py util-test
./full_test_suite.py secp256k1
./full_test_suite.py libsnark
./full_test_suite.py univalue
./full_test_suite.py rpc-ext
./full_test_suite.py rpc-common
Test case that is failing:
./mn_governance.py <-- Failed on master branch also.
Test case that took too long to complete, and failed some test cases while running:
./full_test_suite.py rpc-mn
> Add implementation for z_sendmanywithchangetosender, which will send PSL to an address and return any change to the sending address

- src/mnode/mnode-config.cpp
- src/mnode/mnode-masternode.h
Providing backward compatibility with `try{}catch()` block for reading / writing extP2P parameter only in case it is available. Tested on current mainnet.
> Backward compatibility with old MNs

- qa/rpc-tests/mn_governance.py
Reverts pastelnetwork/pastel#52
This PR is to revert the change from #52 , because that PR didn't get enough 2 approval before merging.
> Revert "Fix issue that cause mn_governance.py failed randomly"

- src/univalue/include/univalue.h
- src/univalue/lib/univalue.cpp
- src/univalue/lib/univalue_read.cpp
- src/univalue/lib/univalue_write.cpp
Integrate univalue PR to support move semathics: https://github.com/jgarzik/univalue/issues/52.
In a benchmark with Bitcoin's BlockToJsonVerbose, using these move
methods where possible speeds up JSON generation by about a factor of 2.
You can see some benchmarks here: bitcoin/bitcoin#20999
> univalue support for move semantics

- build-aux/vs2019/bitcoin_test/bitcoin_test.props
- build-aux/vs2019/pastel_gtest/pastel_gtest.props
- build-aux/vs2019/pasteld/pasteld.props
- build-aux/vs2019/settings/common.props
- build-aux/vs2019/settings/libzmq.props
- depends/funcs.mk
- depends/hosts/default.mk
- depends/hosts/mingw32.mk
- depends/packages/googletest.mk
- depends/packages/zeromq.mk
- src/zmq/zmqpublishnotifier.cpp
- src/zmq/zmqpublishnotifier.h
- updated libzmq library from v4.3.1 (01/12/2019) to v4.3.4 (01/17/2021)
- changed depends package zeromq.mk to support new version,
- converted ZeroMQ build from autotools to cmake
- fixed some warnings in src/zmq related to ZeroMQ usage
- Visual Studio 2019 build:
- added new libzmq.props with ZeroMQ lib configuration
- added libzmq.props to pasteld.props, pastel_gtest.props
> [43158891] Update ZeroMQ library to v4.3.4

- build-aux/vs2019/libbitcoin_server/libbitcoin_server.vcxproj
- build-aux/vs2019/libbitcoin_server/libbitcoin_server.vcxproj.filters
- build-aux/vs2019/libbitcoin_util/libbitcoin_util.vcxproj
- build-aux/vs2019/libbitcoin_util/libbitcoin_util.vcxproj.filters
- qa/rpc-tests/mn_expiration.py
- qa/rpc-tests/mn_tickets.py
- qa/rpc-tests/mn_tickets_username_change.py
- qa/rpc-tests/mn_tickets_validation.py
- qa/rpc-tests/pastel_test_framework.py
- qa/rpc-tests/secure_container.py
- src/Makefile.am
- src/chainparams.h
- src/coins.cpp
- src/gtest/test_mnode/test_pastelid.cpp
- src/main.cpp
- src/mnode/mnode-pastel.cpp
- src/mnode/mnode-pastel.h
- src/mnode/rpc/mnode-rpc.cpp
- src/mnode/rpc/pastelid-rpc.cpp
- src/mnode/rpc/pastelid-rpc.h
- src/mnode/ticket.h
- src/pastelid/pastel_key.cpp
- src/pastelid/pastel_key.h
- src/rpc/rpc_consts.h
- src/scope_guard.hpp
"pastelid newkey" API generates:
- Ed448 private/public key pair, encoded public key becomes PastelID
- LegRoast private/public key pair
All keys are stored locally in the secure container, private keys are encrypted and stored as secure items,
LegRoast public key - not encrypted and stored as a public item.
PastelID can be registered in the blockchain using:
1) tickets register id - to register personal PastelID
2) tickets register mnid - to register MN PastelID
LegRoast public key is now stored in a pq_key fields of the Pastel ID registration ticket.
- added pq_key to the list of fields used to generate signature for Pastel IDreg ticket.
- removed duplicate code for IDReg ticket fields serialization (used for creating signature, verification)
- moved pastelid RPC API to the separate …
> [PSL-3] LegRoast pubkey should be stored in PastelID reg ticket

- qa/rpc-tests/mn_tickets.py
- qa/rpc-tests/mn_tickets_username_change.py
- qa/rpc-tests/pastel_test_framework.py
- qa/rpc-tests/secure_container.py
- qa/rpc-tests/test_framework/test_framework.py
- src/mnode/mnode-pastel.h
- src/pastelid/pastel_key.cpp
Enhanced "pastelid verify" RPC API with 'legroast' algorithm parameter.
New verify command logic:
- if the specified PastelID is stored locally - load legroast public key from the secure container associated with that PastelID
- try to find PastelID registration ticket in the blockchain using PastelID as a key.
If IDreg ticket was found - get legroast public key from that ticket.
Added python tests to secure_container.py to:
- pastelid1 is generated on node0, pastelid3 on node1
- sign text on node1 with the legroast key associated with pastelid3
- check that signature verification fails on node0 (because pastelid3 is not stored locally and not registered in the blockchain)
- register pastelid3 (PastelID registration ticket)
- check that signature verification succeeds on node0. LegRoast …
> [PSL-8] `pastelid verify` API for legroast

- src/bitcoin-cli.cpp
- src/mnode/tickets/ticket-mn-fees.h
- src/pastelid/pastel_key.cpp
- src/pastelid/pastel_key.h
- src/pastelid/secure_container.cpp
PastelID was stored previously in pkcs8 encrypted file using ed448 key and a passphrase.
Later on, storage for PastelID was converted to the secure container file encrypted with xchacha20-poly1305 with the same passphrase.
"pastelid passwd" rpc API is used to change passphrase on the secure container.
Fixed an issue when "pastelid passwd" command is called on the pastel key file in old format.
Change Password algorithm has been changed:
- try to read Pastel Key file as a secure container
- if secure container prefix does not match - try to read ed448 private key from a file in PKCS8 format.
- if ed448 private key successfully read using old passphrase - new secure container is created (created missing legroast private/public key pair).
- write secure container file with the new passphrase …
> [PSL-153] 'pastelid passwd' API does not work for old pkcs8 pastelkey file

- src/crypto/equihash.cpp
- src/crypto/equihash.h
- src/main.cpp
- src/main.h
- src/mnode/mnode-manager.cpp
- src/mnode/mnode-payments.cpp
- src/mnode/mnode-payments.h
- src/protocol.cpp
- src/protocol.h
- src/vector_types.h
- Added extra validation for SuperNode payment transaction.
- This check is activated in Mainnet at blockHeight 228700.
- Before the change, the transaction was considered valid if there were less than 6 votes. After the change, the transaction is checked for payment regardless of the payee vote count.
- Payees are also ordered by vote count in descending order and the payment check is performed first on the payee with max vote count.
- Regular transactions with no votes are considered valid.
- Increased number of MasterNodes participating in voting from 10 to 20
> [PSL-295] MasterNode payment voting fix

- .gitignore
- src/crypto/common.h
- src/mnode/rpc/storage-fee.cpp
- src/mnode/tickets/action-reg.cpp
- src/mnode/tickets/action-reg.h
- src/rpc/server.cpp
- src/rpc/server.h
- treat action fee units as PSL
pastel-cli storagefee getactionfees 0:
{
"datasize": 0,
"sensefee": 265,
"sensefeePat": 26500000,
"cascadefee": 15,
"cascadefeePat": 1500000
}
- added units to all storage fee commands in a usage info
- added fees in patishis (with *Pat suffix) for consistency in other storagefee commands
> [PSL-296] Fix `storagefee getactionfees`

- src/httpserver.cpp
- src/scheduler.cpp
- src/script_check.cpp
- src/svc_thread.h
g++ 9.3 MingW cross-compiler creates incorrect code (with -O1 optimization option) for thread_local variable (c++11 feature).
The code crashes on the first access to thread_local var.
Replaced thread_local with __thread specifier (older gnu thread-local-storage) only for Mingw64 version.
> [PSL-300] MingW pasteld crashes on startup

- src/Makefile.gtest.include
- src/chain.cpp
- src/chain.h
- src/chainparams.cpp
- src/checkpoints.cpp
- src/gtest/test_validation.cpp
- src/main.cpp
- src/main.h
- src/netmsg/block-cache.cpp
- src/netmsg/block-cache.h
When contextual block N validation fails with "missing input tx" error - block is saved to a cache map for revalidation.
After next block N+1 is received - it checks whether previous block is in block cache map.
If yes - it will be added to the unlinked cache multimap [(N block hash) -> (N+1 block hash)].
N+1 block does not have proper values for nTx, nChainTx, nChainSaplingValue fields because block N is not connected yet.
Block N revalidation changes:
- unlock mutex that protects block cache map when calling ProcessNewBlock to avoid recursive mutex call and deadlock
- if block is revalidated - tip is updated to "block N"
- get range of blocks from unlinked cache multimap by "block N" hash, these blocks can be potential next blocks in a chain
- for each unlinked block:
- find block index …
> [PSL-291] block revalidation

- qa/pull-tester/rpc-tests.sh
- moved some slow python tests to the separate group to keep total CircleCI runtime within 2hrs
> [PSL-345] reduce CircleCI runtime

- build-aux/vs2022/libbitcoin_server/libbitcoin_server.vcxproj
- build-aux/vs2022/libbitcoin_server/libbitcoin_server.vcxproj.filters
- qa/rpc-tests/mn_tickets.py
- qa/rpc-tests/test_framework/authproxy.py
- qa/rpc-tests/test_framework/util.py
- src/Makefile.am
- src/metrics.cpp
- src/mnode/rpc/mnode-rpc.cpp
- src/mnode/rpc/tickets-find.cpp
- src/mnode/rpc/tickets-find.h
- src/mnode/rpc/tickets-findbylabel.cpp
- src/mnode/rpc/tickets-findbylabel.h
- src/mnode/ticket-processor.cpp
- src/mnode/ticket-processor.h
- src/mnode/tickets/action-reg.h
- src/mnode/tickets/nft-collection-reg.h
- src/mnode/tickets/nft-reg.h
- added label as a MVkey for the following tickets: NFT Reg, NFT-collection Reg, ActionReg
- added new RPC API to search tickets by label:
tickets findbylabel <ticket-type> "label"
Set of commands to find different types of Pastel tickets by label.
Available ticket types:
nft      - Find NFT registration tickets by label.
nft-collection - Find NFT collection registration tickets by label.
action   - Find action registration tickets by label.
Arguments:
1. "label"   (string, required) The label to use for ticket search. See types above...
This API searches for tickets by MV key (passed via "label" parameter) and returns json array of found tickets.
- added python tests to mn_tickets.py for the new findbylabel API
> [PSL-348] Add RCP API to search NFT,NFT collection, Action tickets by label

- build-aux/vs2022/libbitcoin_server/libbitcoin_server.vcxproj
- build-aux/vs2022/libbitcoin_server/libbitcoin_server.vcxproj.filters
- qa/pull-tester/rpc-tests.sh
- src/Makefile.am
- src/gtest/test_mnode/test_governance.cpp
- src/mnode/mnode-controller.cpp
- src/mnode/mnode-controller.h
- src/mnode/mnode-governance.cpp
- src/mnode/mnode-governance.h
- src/mnode/mnode-notificationinterface.cpp
- src/mnode/mnode-notificationinterface.h
- src/mnode/mnode-sync.cpp
- src/mnode/mnode-validation.cpp
- src/mnode/mnode-validation.h
- src/mnode/rpc/governance-rpc.cpp
- src/mnode/rpc/governance-rpc.h
- src/mnode/rpc/mnode-rpc.cpp
- src/mnode/rpc/pastelid-rpc.cpp
- src/mnode/tickets/action-reg.h
- src/mnode/tickets/ticket-types.h
- src/rpc/mining.cpp
- disable all governance tickets logic depending on macro definition GOVERNANCE_TICKETS (can be defined in mnode/tickets/ticket-types.h)
- block validations
- governance RPC API
- moved mn_governance.py python test to the separate test group (MNdisabled)
> [PSL-352] Disable governance tickets

- .circleci/Dockerfile
- .circleci/config.yml
- build.sh
- src/sync.cpp
- removed 6 duplicate jobs
- configured single job build_platform that will be used to build release/debug for all platforms
- build_platform job supports the following parameters:
- platform: linux, darwin or windows
- debug_mode: true|false
- static_code_analysis: true|false - whether to run PVS static code analyzer
- run_tests: true|false - execute tests
- deploy: true|false deploy release to GitHub & AWS
> build & circle-ci changes:

- qa/pull-tester/rpc-tests.sh
- qa/rpc-tests/mn_bugs.py
- qa/rpc-tests/mn_common.py
- qa/rpc-tests/mn_expiration.py
- qa/rpc-tests/mn_main.py
- qa/rpc-tests/mn_messaging.py
- qa/rpc-tests/mn_payment.py
- qa/rpc-tests/mn_tickets.py
- qa/rpc-tests/mn_tickets_validation.py
- qa/rpc-tests/pastel_test_framework.py
- src/chainparams.cpp
- src/chainparams.h
- src/mnode/mnode-active.cpp
- src/mnode/mnode-config.h
- src/mnode/mnode-controller.cpp
- src/mnode/mnode-controller.h
- src/mnode/mnode-manager.cpp
- src/mnode/mnode-manager.h
- src/mnode/mnode-masternode.cpp
- src/mnode/mnode-masternode.h
- src/mnode/mnode-payments.cpp
- src/mnode/mnode-validation.h
- src/mnode/rpc/masternode.cpp
- src/mnode/rpc/masternodebroadcast.cpp
- src/mnode/tickets/offer.cpp
- src/primitives/transaction.h
- src/rpc/rpc_parser.h
- src/timedata.cpp
- src/uint256.cpp
Added new API for PoSe (Proof-of-Service) Ban score management:
masternode pose-ban-score [get|increment] "txid" index
RPC API parameters validations:
- txid is valid and can be converted to uint256
- index is valid integer
- MN with the given outpoint exists
- exception handling Changed mn_expiration.py:
- use new MasterNode, TopMN classes and new MasterNode initialization with mnid registration
- moved some functions from mn_expiration.py & mn_tickets.py to mn_common.py to get rid of duplicate code
- fixed amounts calculation for NFT transfers (royalty, green fees)
- found and fixed an issue in pasteld with offer ticket replacement validation
- use different number of blocks to allow offer ticket replacement for regtest (288), mainnet, testnet (2880, 5 days)
- added tests for the new …
> [PSL-433] Write API on pasteld to handle score update

- qa/pull-tester/rpc-tests.sh
- qa/rpc-tests/mn_common.py
- qa/rpc-tests/mn_main.py
- qa/rpc-tests/mn_tickets_validation.py
- src/init.cpp
- src/metrics.cpp
- src/mnode/mnode-active.cpp
- src/mnode/mnode-config.cpp
- src/mnode/mnode-config.h
- src/mnode/mnode-controller.cpp
- src/mnode/mnode-manager.cpp
- src/mnode/mnode-manager.h
- src/mnode/mnode-masternode.cpp
- src/mnode/mnode-masternode.h
- src/mnode/mnode-messageproc.cpp
- src/mnode/mnode-msgsigner.cpp
- src/mnode/mnode-payments.cpp
- src/mnode/mnode-sync.cpp
- src/mnode/mnode-sync.h
- src/mnode/rpc/masternode.cpp
- src/mnode/rpc/masternodebroadcast.cpp
- src/mnode/tickets/ticket_signing.cpp
- src/mnode/tickets/username-change.cpp
- src/net.cpp
- src/net.h
- src/pastelid/secure_container.cpp
- src/policy/fees.cpp
- src/rest.cpp
Changed pasteld code to:
- ignore extKey (mnid) while reading masternode's configuration from masternode.conf
- find mnid by Masternode's collateral transaction outpoint (txid+index). This collateral id (txid-index) is used as a secondary index in the MN Pastel ID Registration ticket.
- don't set ENABLED status for active local MN unless MNID is registered and the corresponding secure container exists locally
- refactored masternodebroadcast creation
- check MNID on processing "mnb" (masternode broadcast) message, retrieve mnid by MN's collateral id (txid+index) in mnb.
- removed duplicate code from "masternode start-alias" & "masternode start-all", created common "process_start_alias" function If MNID is not yet registered for this MN, RPC will return now an additional "message": 
{ …
> [PSL-450] Use MN's collateral outpoint to find MN Pastel ID

- src/gtest/test_rpc.cpp
- src/pastel-cli.cpp
- src/rpc/client.cpp
- src/rpc/client.h
Array with RPC method names associated with parameter indexes was used to search for RPC parameters that needed conversion (use non-RFC4627 JSON parser). RPC Param Convert class was changed:
- removed duplicate entries from RPC params initialization array with the same RPC method name, added set of parameter indexes
- added capability to define optional sub-method: for example: { "masternode", "pose-ban-score", {3} } - use non-RFC4627 parsing only for 3rd parameter in "masternode pose-ban-score" API
- on class initialization create an unordered map with key: [method-submethod] - for entries with submethod [method-*] - for APIs without submethod
- improved performance for the search of the RPC parameters that require conversion - search in the hash-map by key is much faster than linear …
> [PSL-471] Accept outpoint index numeric parameter in "pose-ban-score" RPC API

- src/gtest/pastel_gtest_main.h
- src/gtest/test_mnode/test_pastelid.cpp
- src/gtest/test_mnode/test_ticket_processor.cpp
- src/gtest/test_rpccmd_parser.cpp
- src/mnode/rpc/masternode.cpp
- src/mnode/rpc/pastelid-rpc.h
- src/pastelid/pastel_key.h
- src/rpc/rpc_parser.h
- src/wallet/gtest/test_wallet_zkeys.cpp
- added validation for the RPC command parameter type. cNode crashes if RPC command parameter type is not a string.
- corrected RPC help in "masternode list"
> [PSL-478] cNode crashes on invalid RPC command parameter type

- src/deprecation.cpp
- src/gtest/test_deprecation.cpp
- src/main.cpp
- src/mnode/mnode-controller.cpp
- src/mnode/mnode-controller.h
- src/mnode/mnode-governance.cpp
- src/mnode/mnode-manager.cpp
- src/mnode/mnode-manager.h
- src/mnode/mnode-payments.cpp
- src/mnode/mnode-validation.cpp
- src/mnode/rpc/masternode.cpp
- src/mnode/tickets/accept.cpp
- src/mnode/tickets/ticket_signing.cpp
- src/netmsg/block-cache.cpp
- src/netmsg/block-cache.h
- introduced detailed status enum for getting top mns for the given block:
SUCCEEDED              : successfully got top masternodes
SUCCEEDED_FROM_HISTORY : successfully got top masternodes from historical top mn data
MN_NOT_SYNCED          : masternode is not synced
BLOCK_NOT_FOUND        : block not found
GET_MN_SCORES_FAILED   : failed to get masternode scores
NOT_ENOUGH_MNS         : not enough top masternodes
HISTORY_NOT_FOUND      : historical top mn data not found
GetTopMNsForBlock,CalculateTopMNsForBlock,GetMasternodeRanks functions now return this detailed status along with the error message.
- changed ticket signature validation in case MN synced flag is set:
- check if there was an error getting top mns for the ticket creator height - return …
>  [PSL-714] Fit it so a node won't reject a block as being invalid just because it was signed by an SN that the node had already banned

- src/chain.cpp
- src/chain.h
- src/deprecation.h
- src/httprpc.h
- src/main.cpp
- src/mnode/mnode-manager.cpp
- src/mnode/mnode-manager.h
- src/mnode/mnode-payments.cpp
- src/mnode/mnode-payments.h
- src/mnode/ticket-processor.cpp
- src/mnode/ticket-processor.h
- src/mnode/tickets/accept.cpp
- src/mnode/tickets/action-act.cpp
- src/mnode/tickets/action-reg.cpp
- src/mnode/tickets/collection-act.cpp
- src/mnode/tickets/collection-item.cpp
- src/mnode/tickets/collection-reg.cpp
- src/mnode/tickets/etherium-address-change.cpp
- src/mnode/tickets/nft-act.cpp
- src/mnode/tickets/nft-reg.cpp
- src/mnode/tickets/nft-royalty.cpp
- src/mnode/tickets/offer.cpp
- src/mnode/tickets/ticket-utils.h
- src/mnode/tickets/ticket.h
- src/mnode/tickets/transfer.cpp
- src/mnode/tickets/username-change.cpp
Changed all functions that retrieve tickets from TicketDB - added validation for the ticket height, if the ticket height is greater than active chain height - ignore this ticket. That will ensure proper ticket validation - no tickets with a height greater than the active chain height will be used for validation.
> [PSL-758] pasteld: two Accept tickets for the same Offet ticket in a block

- src/mnode/mnode-controller.cpp
- src/mnode/mnode-requesttracker.cpp
- src/mnode/mnode-requesttracker.h
- src/mnode/tickets/collection-item.cpp
- src/mnode/tickets/collection-reg.cpp
- src/mnode/tickets/collection-reg.h
**[PSL-782] Put a cap on the number of entries in `list_of_pastelids_of _authorized_contributors` in collection tickets**
- added validation for collection reg ticket in pre-reg, allow max 250 authorized contributors
**[PSL-788] cNode: define nFulfilledRequestExpireTime for testnet**
[PSL-782]: https://pastel-network.atlassian.net/browse/PSL-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PSL-788]: https://pastel-network.atlassian.net/browse/PSL-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PSL-782] Put a cap on the number of entries in `list_of_pastelids_of _authorized_contributors` in collection tickets

- qa/rpc-tests/mn_bugs.py
- qa/rpc-tests/mn_common.py
- qa/rpc-tests/mn_expiration.py
- qa/rpc-tests/mn_tickets.py
- qa/rpc-tests/reorg_limit.py
- src/chain.cpp
- src/chain.h
- src/gtest/test_alert.cpp
- src/main.cpp
- src/mnode/mnode-controller.cpp
- src/mnode/rpc/tickets-activate.cpp
- src/mnode/tickets/pastelid-reg.cpp
- src/net.cpp
- src/net.h
- src/net_manager.cpp
- src/rpc/mining.cpp
- changed minimum confirmation for registration tickets from 10 to 5
- corrected python tests for the new confirmation count, redesigned some tests to use MIN_TICKET_CONFIRMATIONS variable instead of harcoding
- removed getting chain height under cs_main lock in few missed places (use atomic gl_nChainHeight variable)
- added an ability to stop on signal while checking internet connectivity in hasInternetConnectivity, CNetManagerThread thread. hasInternetConnectivity function pinging 4 hosts from the list, if network is unreachable - this could take a lot of time and afffect shutdown time, some python tests also could fail because of this
> [PSL-798] Change required minimum confirmation for registration tickets from 10 to 5

- depends/packages/boost.mk
- depends/packages/zstd.mk
- src/mnode/mnode-payments.h
- src/serialize.h
- upgraded zstd package to v1.5.5 (released 04/04/2023)
[PSL-757] pasteld: upgrade boost library to the latest version 1.82
- upgraded boost package to v1.82 (released 04/14/2023)
[PSL-858] mnpayments.dat protected mode fix
[PSL-757]: https://pastel-network.atlassian.net/browse/PSL-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PSL-858]: https://pastel-network.atlassian.net/browse/PSL-858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PSL-756] pasteld: upgrade zstd to version 1.5.5

- src/init.cpp
- src/mnode/mnode-controller.cpp
- src/mnode/mnode-controller.h
- src/mnode/mnode-manager.cpp
- src/mnode/mnode-manager.h
- src/mnode/rpc/masternode.cpp
- src/mnode/tickets/ticket_signing.cpp
1. Added new API: `masternode clear-cache all` - it will clear all lists used by CMasternodeMan: 
- masternodes, 
- seen broadcasts and pings 
- recovery requests and replies. 
2. Added check for enough Enbaled MNs when checking signing MNs in tickets
3. Added paslted parameters 'setminenabledmncount' and 'setminenabledmnpercent', and API calls 'masternode min-enabled-mn-count' and 'masternode min-enabled-mn-percent' to set criteria to check for enough Enabled MNs when checking signing MNs in tickets
> Masternode fixes

- src/deprecation.h
- src/gtest/test_coins.cpp
- src/gtest/test_rpc.cpp
- src/gtest/test_rpc_wallet.cpp
- src/mnode/rpc/tickets-list.cpp
- src/mnode/ticket-processor.cpp
- src/mnode/tickets/action-act.cpp
- src/mnode/tickets/collection-act.cpp
- src/mnode/tickets/nft-act.cpp
- src/rpc/misc.cpp
- src/rpc/server.cpp
- src/wallet/rpcwallet.cpp
[PSL-960] pasteld: pastel-cli help
- fixed help rpc command without parameters - should return a list of all available RPC commands sorted by categories
[PSL-924] pasteld: filter offer/accept/transfer tickets as well using the same cutoff (block 265,000 in testnet) so things are consistent
- set default minheight to 265'000 when listing tickets of the following types in testnet: action-reg, action-act, nft-reg, nft-act, offer(sell), accept(buy), transfer(trade), collection-reg, collection-act
[PSL-960]: https://pastel-network.atlassian.net/browse/PSL-960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PSL-924]: https://pastel-network.atlassian.net/browse/PSL-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> [PSL-960] pasteld: pastel-cli help

- src/init.cpp
- src/mnode/mnode-manager.cpp
- src/mnode/mnode-masternode.h
- src/util.cpp
- src/util.h
[PSL-961]  cNode: printtoconsole feature enhancement
Enhanced printtocaonsole option to support few modes:
0 - do not output any messages to console, log only to debug.log file
1 - output debug messages only to console
2 - output debug messages to both console and debug.log
printtoconsole modes 1 & 2 disable showmetrics
- fixed MN ping time check function IsPingedWithin - responsible for bad MN state changes
[PSL-961]: https://pastel-network.atlassian.net/browse/PSL-961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PSL-961]  cNode: printtoconsole feature enhancement

- src/chain.cpp
- src/main.cpp
- src/mnode/mnode-active.cpp
- src/mnode/mnode-manager.cpp
- src/mnode/mnode-manager.h
- src/mnode/mnode-sync.cpp
- src/mnode/rpc/masternode.cpp
- src/netmsg/block-cache.cpp
- src/netmsg/block-cache.h
- src/reverselock.h
- src/rpc/blockchain.cpp
When block is missing dependencies - it is placed into block cache for revalidation and then it tries 
to revalidate it up to 20 times with 3 secs interval (TTL=20*3 = 60 secs). After max attempts are reached - 
block is rejected and the ban score is increased by 10 points for that node. If download is too slow -
nodes become blocked sooner than blocks can be revalidated. Eventually, all the nodes are getting banned 
and download stalls.
- removed check for max revalidation attempts counter
- block cached for revalidation can stay in the cache until:
- blockchain tip advanced already beyound that block height
- it is successfully revalidated
- fails on revalidation with the error other than REJECT_MISSING_INPUTS (missing dependent transactions)
- expires after …
> [PSL-971] cNode: IBD stalls when revalidation from block cache bans all peers

- src/chainparams.cpp
- src/consensus/params.h
- src/consensus/upgrades.cpp
- src/version.h
pasteld v2.0.0.0
- added new Monet upgrade with release height 575'000 (mainnet), 367'000 (testnet)
- protocol version changed to 170010, min supported MN protocol version 170009
> [PSL-1021] pasteld: Monet release

- configure.ac
- src/chainparams.cpp
pasteld v2.1.0-beta1
- changed Monet release height for testnet to 370'000
> pasteld: update Monet release height for testnet

- depends/packages/openssl.mk
- updated openssl package in depends from v3.0.0 to v3.1.4 (10/24/2023)
> [PSL-424] Update OpenSSL to fix sha-3 buffer overflow vulnerability

- build-aux/vs2022/libbitcoin_server/libbitcoin_server.vcxproj
- build-aux/vs2022/libbitcoin_server/libbitcoin_server.vcxproj.filters
- qa/rpc-tests/mn_main.py
- src/Makefile.am
- src/rpc/blockchain.cpp
- src/rpc/coin-supply.cpp
- src/rpc/coin-supply.h
- added new RPC API to calculate total coin supply for the current height get-total-coin-supply
{
"result": {
"totalCoinSupplyPat": 1449125105336874,
"totalCoinSupply": 14491251053.36874,
"height": 597645
},
"error": null,
"id": "1"
}
The initial implementation was traversing the whole blockchain and summing up coinbase transactions. It was slow (12 mins) and held cs_main lock for the whole duration of the calculation. 
Changed implementation:
- collect under cs_main all information about block data location in the block db: block location is identified by block file number and offset. Block location info is stored into the map: <file_no, offsets_vector>.
- sort offsets in the vectors in ascending order to access block data in the file sequentially (improves speed)
- all offset vectors …
> [PSL-1101] pasteld: add API to get total coin supply for the current height

- src/main.cpp
- src/mining/eligibility-mgr.cpp
- src/mining/eligibility-mgr.h
- src/mining/miner.cpp
- src/rpc/mining.cpp
- src/utils/svc_thread.h
If MN eligibility validation fails on one block - this block is marked invalid and the chain stalls.
Cache this block info to eligibility manager to revalidate later. This invalid block is revalidated in eligibility manager thread up to 3 times: at 6,16 and 31 mins after it was cached. Block revalidation does the following:
- checks if active chain has already passed that block height - cached block info cleared in this case
- finds block index by hash
- calls reconsiderblock and then ActivateBestChain
- checks if the active chain passed cached block height after ActivateBestChain call - clears invalid cached block info
> [PSL-1134] Failed MN Eligibility block revalidation

- qa/rpc-tests/mn_common.py
- qa/rpc-tests/mn_main.py
- qa/rpc-tests/mn_tickets_validation.py
- src/chainparams.cpp
- src/mining/miner.cpp
- src/mining/miner.h
- src/mining/mining-settings.cpp
- src/mining/mining-settings.h
- src/mnode/mnode-active.cpp
- src/mnode/mnode-active.h
- src/mnode/mnode-config.cpp
- src/mnode/mnode-config.h
- src/mnode/mnode-masternode.cpp
- src/mnode/rpc/masternode.cpp
- src/mnode/rpc/masternode.h
- src/rpc/mining.cpp
- changed Vermeer upgrade height to 648'500
- changed min difficulty filter for devnet to 29'000 (same as upgrade height)
- moved genenablemnmining option to masternode.conf: new option name: "enableMnMining"
- changes in CMinerSettings class: - read only "genpassphrase" option from pastel.conf, don't read options -genpastelid or -genenablemnmining - get GenId from local active masternode
- PastelMiner thread:
- check for valid mn mining settings (check is activated only after Vermeer upgrade): - MN has registered MNID (locally) - passphrase is defined in pastel.conf - secure container can be accessed using passphrase - enableMnMining option is enabled
- set eligibleForMining flag in mnb (masternode broadcast) from MasterNode config entry
> Vermeer mining options changes

- configure.ac
- src/clientversion.h
- src/rpc/mining.cpp
- src/wallet/rpcwallet.cpp
scanburntransactions "from_taddress" ( hash|height ) ( burn_taddress ) Scan for the transactions from the given transparent address to the burn address.
Arguments:
1. "from_taddress" (string, required) The transparent address that the transactions are sent from. If '*' is given, will scan for transactions from all addresses.
2. hash|height     (string or numeric, optional) The block hash or height to start scanning from.
If not provided, the scan starts from the genesis block.
3. burn_taddress   (string, optional) The burn address to scan for. If not provided, the default burn address is used.
> [PSL-1172] pasteld: add optional burn address parameter to scanburntransactions API

- .circleci/DockerBuild.bat
- .circleci/Dockerfile
- .circleci/config.yml
- build-aux/vs2022/pasteld/pasteld.vcxproj
- build-aux/vs2022/pasteld/pasteld.vcxproj.filters
- configure.ac
- depends/packages/bdb.mk
- depends/packages/boost.mk
- depends/packages/googletest.mk
- depends/packages/zstd.mk
- src/clientversion.h
- src/gtest/test_httprpc.cpp
- src/gtest/test_rpc_wallet.cpp
- src/httprpc.cpp
- src/httpserver.cpp
- src/httpserver.h
- src/init.cpp
- src/metrics.cpp
- src/mining/miner.cpp
- src/mining/pow/tromp/equi_miner.h
- src/txdb/txdb.cpp
- src/wallet/rpcwallet.cpp
pasteld v2.2.6
Added separate class to keep information about HTTP Connection.
Now requests coming from the existing keep-alive http connection create
only HTTPRequest object without connection info.
HTTPRequest object lifetime is now limited to http_request_cb callback.
Save http connections only in unordered_map with client socket as a key (CHttpWorkerContext).
- added accept error handler.
- improved logging
other changes:
- returned c++20/gcc-11 changes for Linux
- added Ctrl-C console handler for Windows to shutdown pasteld
- improved shutdown when pasteld is still in initialization mode (added some checks to exit earlier)
>  [PSL-1229] pasteld: handle keep-alive connections
